README.md
@lirantal WDYT about Dynamic Analysis? Worth adding a section? I can add Zaproxy to there, maybe also worth adding burp.
=> Added DevSkim

README.md
Adding https://nodesecroadmap.fyi
=> docs(articles): add Node.js Security Roadmap

README.md
Hello @lirantal, 
good job on that list!
I've added a company entry for GuardRails.
=> Add GuardRails to Companies

README.md
Adding a new incidents section.
There are a bunch more to add which I'll follow-up on shortly as well.
=> docs(incidents): add new section

README.md
Adding references for the getcookies incident
=> docs(incidents): getcookies malicious npm package

README.md
=> Fix broken link in the README table of contents

README.md
Secure composition is creating an output by combining trusted and untrusted parts while preserving the intent of the trusted parts and preventing untrusted parts from specifying high privilege instructions.
I put this after Input/Output Encoding because secure composition is related to encoding -- secure composition relieves the developer of the burden of picking the right encoders.
=> Added a section on secure composition

README.md
Update to add supporting links for the crossenv incident
=> docs(incidents): crossenv

README.md
Add the 10 npm security best practices article as a resource
=> docs(articles): add npm security cheat sheet

README.md
- Add links to the EasyDEX-GUI incident
- Fix other links to a consistent format of using commas between references
=> docs(incident): add EasyDEX-GUI cryptocurrency

README.md
Add Trust But Verify (TBV) package
=> docs(analysis): tbv

README.md
Adding [lockfile-lint](https://github.com/lirantal/lockfile-lint) as a linter to the static analysis list
=> docs(analysis): add lockfile-lint

README.md
=> docs(analysis): add pkgsign

README.md
Add Node.js Security Cheat Sheet from OWASP Cheat Sheet Series to Articles
=> Add Node.js Security Cheat Sheet

README.md
Not sure if this post can fit here @lirantal ;-)
=> Added backdoor article

README.md
Thank you @lirantal  for putting this list together. 
This PR is to add Shieldfy to the list of companies that helps with Nodejs security.
=> Add Shieldfy to the list of Companies

README.md
What do you think @lirantal ?
Seems quite used (10k/w) what 6 years ago the last request.
=> add express-enforces-ssl

README.md
DomGoat is a great resource to learn how sources and sinks can lead to XSS.
=> Add DomGoat

README.md
The correct link is https://github.com/ajinabraham/nodejsscan
=> Update Readme file with the correct nodejsscan repository link

README.md
Hi @lirantal! Thanks for this list--I thought I should add [semgrep](https://semgrep.dev) to the list of static analysis tools.
=> Add semgrep

README.md
PR to add my package js-x-ray to the list of static analysis tool!
=> docs(analysis): add js-x-ray

README.md
Just saw fastify was missing on the list.
=> docs(tools): added fastify-helmet to hardening

README.md
I'm not used to be a collaborator.
So I believe I should wait for another member approval right?
=> Fastify csrf and rate-limit

README.md
Hi,
I would like to contribute to this list by adding a new CLI tool named [joi-security](https://github.com/Saluki/joi-security). The goal of this tool is to analyze Joi validation schemas and detect potential security flaws such as XSS attacks, SQL injections or path traversal attempts (allowing developers to strenghten their validation schemas).
Thanks!
=> Add joi-security CLI to vulnerabilities list

README.md
This repository is archived by owner and for all intents and purposes dead.
=> Remove Archived Repository

README.md
PurpleTeam has two main environments `local` and `cloud`.
* `local` is OWASP - set everything up yourself in your own environment
* `cloud` is a proprietary offering with everything hosted for you in the cloud. You just need to configure and run the CLI
PurpleTeam is pluggable, if it doesn’t have a tester that you need you can add your own. One of the testers (the web application tester) uses OWASP ZAP under the hood.
=> Add PurpleTeam to new DAST section

README.md
Ooops... Missed the Contents heading
=> Fix Contents for DAST

README.md
=> add NodeSecure to companies section

README.md
=> Remove intrinsic

README.md
Add `Top 11 Node.js security best practices` from [blog.sqreen.com](https://blog.sqreen.com/nodejs-security-best-practices/) to the ***articles*** section of the page.
```diff
+ -[Top 11 Node.js security best practices | Sqreen.com](https://blog.sqreen.com/nodejs-security-best-practices/)
```
=> Add new article

README.md
Add the [sdc-check](https://github.com/mbalabash/sdc-check) tool created by @mbalabash to the list of static code analysis tool.
=> docs: add sdc-check to static code analysis

README.md
Adding Thoma's book, and removing intrinsic from the list
=> docs: add Thomas's Node.js book

README.md
Adding [Bearer](https://github.com/Bearer/bearer) to the static code analysis section.
=> Adding a Static Code Analysis tool

README.md
PR to add GuardDog (SAST tool by Datadog).
=> docs(tools): add GuardDog

README.md
Added "data-guardian" to the list of "Input Validation & Output Encoding"
=> added "data-guardian" npm package
